deployment:
  tasks:
    - export DEPLOYPATH=/home/premakkt/inventory.devdesigngrow.com/
    - /home/premakkt/bin/composer install --no-dev --optimize-autoloader --no-interaction --working-dir=$DEPLOYPATH
    - php $DEPLOYPATH/artisan migrate --force
    - (php $DEPLOYPATH/artisan storage:link || true)
    - php $DEPLOYPATH/artisan config:clear
    - php $DEPLOYPATH/artisan config:cache
    - php $DEPLOYPATH/artisan route:cache
    - php $DEPLOYPATH/artisan view:cache
    - chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache
